config/routes.rb
Rails.application.routes.draw do
  root 'csv#index'
  resources :csv, only: [:index] do
    get :units, on: :collection
    get :suppliers, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sku.rb
class Sku < ApplicationRecord
  validates :sku, :supplier_code, :name, :price, presence: true
  belongs_to :supplier, primary_key: 'code', foreign_key: 'supplier_code', class_name: 'Supplier'
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :code, :name, presence: true
  has_many :units, class_name: 'Sku', primary_key: 'code', foreign_key: 'supplier_code'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/csv_controller.rb
class CsvController < ApplicationController
  def index
  end

  def units
    @units = Sku.all.page(params[:page]).per(params[:per])
  end

  def suppliers
    @suppliers = Supplier.all.page(params[:page]).per(params[:per])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/csv/index.html.erb
<%= link_to 'Suppliers', suppliers_csv_index_path %>
<%= link_to 'Units', units_csv_index_path %>

app/views/csv/suppliers.html.erb
<h3>Suppliers</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
  </tr>

  <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.name %></td>
        <td><%= supplier.code %></td>
      </tr>
  <% end %>
</table>

<%= paginate @suppliers %>

app/views/csv/units.html.erb
<h3>Units</h3>
<table>
  <tr>
    <th>SKU</th>
    <th>Supplier code</th>
    <th>Name</th>
    <th>Price</th>
  </tr>

  <% @units.each do |sku| %>
      <tr>
        <td><%= sku.sku %></td>
        <td><%= sku.supplier_code %></td>
        <td><%= sku.name %></td>
        <td><%= sku.price %></td>
      </tr>
  <% end %>
</table>

<%= paginate @units %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Csv</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>